--- #YAML:1.0
name:               Net-SMS-VoipBuster
version:            0.04
abstract:           Send SMS from VoipBuster
author:
    - Filipe Dutra <mopy@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Crypt::SSLeay:        0
    IO::Socket::SSL:      0
    LWP::UserAgent:       0
    XML::Parser:          0
    XML::XPath:           1.13
    XML::XPath::XMLParser:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
